export const Names = [
    "advancement",
    "attribute",
    "ban",
    "ban-ip",
    "banlist",
    "bossbar",
    "clear",
    "clone",
    "damage",
    "data",
    "datapack",
    "debug",
    "defaultgamemode",
    "deop",
    "difficulty",
    "effect",
    "enchant",
    "execute",
    "experience",
    "fill",
    "fillbiome",
    "forceload",
    "function",
    "gamemode",
    "gamerule",
    "give",
    "help",
    "item",
    "jfr",
    "kick",
    "kill",
    "list",
    "locate",
    "loot",
    "me",
    "msg",
    "op",
    "pardon",
    "pardon-ip",
    "particle",
    "perf",
    "place",
    "playsound",
    "publish",
    "random",
    "recipe",
    "reload",
    "return",
    "ride",
    "save-all",
    "save-off",
    "save-on",
    "say",
    "schedule",
    "scoreboard",
    "seed",
    "setblock",
    "setidletimeout",
    "setworldspawn",
    "spawnpoint",
    "spectate",
    "spreadplayers",
    "stop",
    "stopsound",
    "summon",
    "tag",
    "team",
    "teammsg",
    "teleport",
    "tell",
    "tellraw",
    "tick",
    "time",
    "title",
    "tm",
    "tp",
    "transfer",
    "trigger",
    "w",
    "weather",
    "worldborder",
    "xp",
] as const;

export const Selectors = ["a", "e", "r", "p", "s"] as const;

export const ExecuteSubcommands = [
    "align",
    "anchored",
    "as",
    "at",
    "facing",
    "in",
    "on",
    "positioned",
    "rotated",
    "store",
    "summon",
    "if",
    "unless",
    "run",
] as const;

export const SelectorArguments = [
    "x",
    "y",
    "z",
    "distance",
    "dx",
    "dy",
    "dz",
    "x_rotation",
    "y_rotation",
    "scores",
    "tag",
    "team",
    "name",
    "type",
    "predicate",
    "nbt",
    "level",
    "gamemode",
    "advancements",
    "limit",
    "sort",
] as const;

export const CommandDataType = [
    "String",

    "Double",
    "FloatRange",
    "NonNegativeFloat",

    "Integer",
    "NonNegativeInteger",

    "ScoreObject",
    "AdvancementObject",

    "SortingValue",
    "GamemodeValue",

    "EntityIdOrTag",
    "SNBT",
] as const;

export const SelectorArgumentsToArgDataTypeMap = new Map<
    (typeof SelectorArguments)[number],
    (typeof CommandDataType)[number]
>([
    ["advancements", "AdvancementObject"],
    ["distance", "FloatRange"],
    ["dx", "NonNegativeFloat"],
    ["dy", "NonNegativeFloat"],
    ["dz", "NonNegativeFloat"],
    ["gamemode", "GamemodeValue"],
    ["level", "FloatRange"],
    ["limit", "NonNegativeInteger"],
    ["name", "String"],
    ["nbt", "SNBT"],
    ["predicate", "String"],
    ["scores", "ScoreObject"],
    ["sort", "SortingValue"],
    ["tag", "String"],
    ["team", "String"],
    ["type", "EntityIdOrTag"],
    ["x", "Double"],
    ["x_rotation", "FloatRange"],
    ["y", "Double"],
    ["y_rotation", "FloatRange"],
    ["z", "Double"],
]);
